pipeline {
    agent any
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Pass the name of branch to build from ')
        string(name: 'REPO_URL', defaultValue: 'https://github.com/dupsy-hub/learning-jenkins-repo.git', description: 'Pass the Repository url to build from ')
    }
    environment { 
        BRANCH = "${params.BRANCH}"
        REPO_URL = "${params.REPO_URL}"
    }
    stages {
        stage('Clone Github Repo') {
            steps {
                script {
                    git branch: "${BRANCH}", credentialsId: 'jenkins-github-creds', url: "${REPO_URL}"
                }
                
            }
        }
        stage('Building Docker Image') {
            steps {
                script {
                    // withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh """
                    cd ${WORKSPACE}/docker
                    docker build -t neogym-html .
                    """
                }
                
            }
                
        }
        stage('Push To Dockerhub Registory') {
            steps {
                script{
                    // withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh """
                    docker push dupsy/neogym-html-repo:v001
                    """
                }
                
            }
        }       
    }
}
    
