pipeline {
    agent any
    parameters {
        string(name: 'BRANCH', defaultValue: 'main', description: 'Pass the name of branch to build from ')
        string(name: 'REPO_URL', defaultValue: 'https://github.com/dupsy-hub/learning-jenkins-repo.git', description: 'Pass the Repository url to build from ')
    }
    environment { 
        BRANCH = "${params.BRANCH}"
        REPO_URL = "${params.REPO_URL}"
    }
    stages {
        stage('Clone Github Repo') {
            steps {
                script {
                    git branch: "${BRANCH}", credentialsId: 'jenkins-github-creds', url: "${REPO_URL}"
                }
                
            }
        }
        stage('Building Docker Image') {
            steps {
                script {
                    // withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'jenkins-aws-creds', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    
                    dir('docker') {
                        sh "docker build -t neogym-html ."
                    }           
                    
                
                }
                
            }
                
        }
        stage('Push To Dockerhub Registory') {
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'jenkins_dockerhub_creds', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                        sh """
                        docker login --username="$USERNAME" --password="$PASSWORD"
                        docker tag neogym-html dupsy/neogym-html-repo:v001
                        docker push dupsy/neogym-html-repo:v001
                        """
                    }
                    
                }
                
            }
        }
        stage('Deploy On Remote Server') {
            steps{
                script {
                    sshPublisher(
                        continueOnError: false, failOnError: true,
                        publishers: [
                                sshPublisherDesc(
                                    configName: "test-server",
                                    verbose: true,
                                    transfers: [
                                        sshTransfer(
                                            sourceFiles: "",
                                            removePrefix: "",
                                            remoteDirectory: "",
                                            execCommand: "docker run -itd --name neogym-app -p 80:80 dupsy/neogym-html-repo:v001"
                                        )
                                    ]
                                )
                        ]
                    )
                }
            }
            
        }       
    }
}
    
